language: php
php:
  - 7.0
  - 7.1
  - 7.2

script:
  - php vendor/bin/phpcs --standard=./test/codesniffer.xml --encoding=utf-8 --extensions=php -p -s lib
  - php vendor/bin/phpunit -c test/phpunit.xml